<a href="https://colab.research.google.com/github/OlexiyBerdichevskie/Numerical-methods/blob/main/%D0%91%D0%B5%D1%80%D0%B4%D0%B8%D1%87%D0%B5%D0%B2%D1%81%D1%8C%D0%BA%D0%B8%D0%B9_%D0%9E%D0%BB%D0%B5%D0%BA%D1%81%D1%96%D0%B9_%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0%E2%84%964_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Бердичевьский Олексій Варіант1 Був присутній на парі

In [1]:
import numpy as np
a = np.array([
    [14, 4, 6],
    [5, -3, 2],
    [10, -11, 5],
])
b = np.array([[30], [15], [36]])

In [2]:
#Матричний метод (1 спосіб)
det_a = np.linalg.det(a)
if det_a == 0:
    print("Визначник дорівнює нулю - рішень немає")
else:
  a_inv = np.linalg.inv(a)
  print(f"Обернена матриця до матриці A: \r\n {a_inv }")
  print(f"Вектор рішення: \r\n {a_inv.dot(b)}")

Обернена матриця до матриці A: 
 [[-0.09722222  1.19444444 -0.36111111]
 [ 0.06944444 -0.13888889 -0.02777778]
 [ 0.34722222 -2.69444444  0.86111111]]
Вектор рішення: 
 [[ 2.]
 [-1.]
 [ 1.]]


In [3]:
# Напиши функцію для вирішення системи матричним методом (2 спосіб)
def solve_inv_matrix(a, b, verbose=False):
    det = np.linalg.det(a)
    if verbose: print(f"Визначник матриці A: {round(det)}")
    if det == 0:
        print("Визначник дорівнює нулю - рішень немає")
        return None

    a_inv= np.linalg.inv(a)
    if verbose: print(f"Обернена матриця до матриці A: \r\n {a_inv }")
    return a_inv.dot(b)

print(f"Вектор рішення: \r\n {solve_inv_matrix(a, b)}")

Вектор рішення: 
 [[ 2.]
 [-1.]
 [ 1.]]


In [4]:
#метод Крамера (1 спосіб)
# Метод Крамера
det_a = np.linalg.det(a)

if det_a == 0:
    print("Визначник дорівнює нулю — система не має єдиного розв’язку.")
else:
    def replace_column(matrix, column_index, new_column):
        new_matrix = np.copy(matrix)
        new_matrix[:, column_index] = new_column
        return new_matrix

    # Обчислюємо Δx, Δy, Δz
    delta_x = np.linalg.det(replace_column(a, 0, b.T))
    delta_y = np.linalg.det(replace_column(a, 1, b.T))
    delta_z = np.linalg.det(replace_column(a, 2, b.T))

    # Обчислюємо x, y, z
    print('x =', delta_x / det_a)
    print('y =', delta_y / det_a)
    print('z =', delta_z / det_a)



x = 2.0000000000000018
y = -1.0
z = 0.9999999999999972


In [5]:
# Напиши функцію для вирішення системи методом Крамера
def solve_cramer(a, b, verbose=False):
    det = np.linalg.det(a)
    if verbose: print(f"Визначник матриці A: {round(det)}")
    if det == 0:
        print("Визначник дорівнює нулю - рішень немає")
        return None

    len_a = len(a)
    x = np.zeros((len_a, 1))
    for i in range(len_a):
        temp = np.copy(a)
        temp[:, [i]] = b
        x[i, 0] = np.linalg.det(temp)/det

    return x


print(f"Вектор рішення: \r\n {solve_cramer(a, b)}")

Вектор рішення: 
 [[ 2.]
 [-1.]
 [ 1.]]


Перевірка

In [6]:
x = np.linalg.solve(a, b)

print(x)

[[ 2.]
 [-1.]
 [ 1.]]


In [8]:
# Напиши функцію для вирішення системи методом Гауса
def solve_gausse(a, b, verbose=False):
    det = np.linalg.det(a)
    if verbose: print(f"Визначник матриці A: {round(det)}")
    if det == 0:
        print("Визначник дорівнює нулю - рішень немає")
        return None
    # Reading number of unknowns
    n = len(b)
    m = np.concatenate([a, b], axis=1, dtype=float)

    # Applying Gauss-Jordan Elimination
    for i in range(n):

        # Swap rows to avoid division by 0
        if m[i, i] == 0:
            for k in range(i+1, n):
                if m[k, k] != 0:
                    m[[i, k], :] = m[[k, i], :]
                    break


        if m[i, i] != 1:
            m[i, :] *= 1/m[i, i]

        for j in range(n):
            if i != j:
                ratio = m[j][i]/m[i][i]

                m[j, :] = m[j, :] - ratio * m[i, :]

    return m[:, [-1]]

print(f"Вектор рішення: \r\n {solve_gausse(a, b)}")

Вектор рішення: 
 [[ 2.]
 [-1.]
 [ 1.]]
