<a href="https://colab.research.google.com/github/OlexiyBerdichevskie/Numerical-methods/blob/main/%D0%91%D0%B5%D1%80%D0%B4%D0%B8%D1%87%D0%B5%D0%B2%D1%81%D1%8C%D0%BA%D0%B8%D0%B9_%D0%9E%D0%BB%D0%B5%D0%BA%D1%81%D1%96%D0%B9_%D0%9B%D0%A0%E2%84%964_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Встaновити numpy
#!pip install numpy

In [ ]:
# Приклади роботи з матрицями
import numpy as np
# Отримання версії бібліотеки NumPy
numpy_version = np.__version__
numpy_version


'2.0.2'

In [ ]:
#1.
matrix = np.random.randint(1, 6, size =(3, 3))

matrix

array([[1, 2, 3],
       [4, 5, 1],
       [4, 4, 3]])

In [ ]:
#2.
det = np.linalg.det(matrix)
det

np.float64(-17.0)

In [ ]:
#3.
product = np.prod(matrix)
product

np.int64(5760)

In [ ]:
#4.
sum = np.sum(matrix)
sum

np.int64(27)

In [ ]:
#5.
max_element = np.max(matrix)
print("Найбільший елемент матриці ", max_element)
min_element = np.min(matrix)
print("Найменший елемент матриці ", min_element)

Найбільший елемент матриці  5
Найменший елемент матриці  1


In [ ]:
# 6.
mean = np.mean(matrix)
mean

np.float64(3.0)

In [ ]:
#7
sqrt_matrix = np.sqrt(matrix)
sqrt_matrix

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 1.        ],
       [2.        , 2.        , 1.73205081]])

In [ ]:
# 8
row_suns = np.sum(matrix, axis = 1).reshape(-1, 1)
row_suns

array([[ 6],
       [10],
       [11]])

In [ ]:
# 9
vector = np.random.randint(0, 10, size = 25)
print("Початковий вектор:")
print(vector)
sorted_vector = np.sort(vector)[::-1]
print("Відсортований вектор:")
print(sorted_vector)

Початковий вектор:
[0 4 0 8 5 4 3 7 5 2 2 4 5 0 0 8 5 4 0 7 3 5 5 6 0]
Відсортований вектор:
[8 8 7 7 6 5 5 5 5 5 5 4 4 4 4 3 3 2 2 0 0 0 0 0 0]


In [ ]:
#10
from scipy import stats
mode = stats.mode(vector)
median = np.median(vector)
mean = np.mean(vector)
max_value = np.max(vector)
min_value = np.min(vector)
print(mode)
print(median)
print(mean)
print(max_value)
print(min_value)

ModeResult(mode=np.int64(0), count=np.int64(6))
4.0
3.68
8
0


In [ ]:
# 11
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

print(matrix1)
print(matrix2)

matrix_sum = matrix1 = matrix2
matrix_diff = matrix1 = matrix2
matrix_product = matrix1 = matrix2
matrix_division = np.divide(matrix1, matrix2, where=(matrix2!=0))
print(matrix_sum)
print(matrix_diff)
print(matrix_product)

[[ 4  9  5  4]
 [ 8 10  2  9]
 [ 2  6  2 10]
 [ 4  1  3  3]]
[[ 4  7  9  4]
 [ 2  5 10  1]
 [ 4  9  5  1]
 [ 7  2 10  3]]
[[ 4  7  9  4]
 [ 2  5 10  1]
 [ 4  9  5  1]
 [ 7  2 10  3]]
[[ 4  7  9  4]
 [ 2  5 10  1]
 [ 4  9  5  1]
 [ 7  2 10  3]]
[[ 4  7  9  4]
 [ 2  5 10  1]
 [ 4  9  5  1]
 [ 7  2 10  3]]


In [ ]:
# 12
x = np.arange(9.0)
x


array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
x1 = x.reshape((3, 3))
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [ ]:
x2 = np.arange(3.0)
np.multiply(x1, x2)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

In [ ]:
#13
x1 = np.arange(6)
x1

array([0, 1, 2, 3, 4, 5])

In [ ]:
np.power(x1, 3)

array([  0,   1,   8,  27,  64, 125])

In [ ]:
# 14
x2 = np.array([1, 2, 3, 3, 2, 1])
x1 = np.arange(6)
x1**x2

array([ 0,  1,  8, 27, 16,  5])

Висновок: на цій лабораторній роботі я восконалив навички працювання з матрицями, а також робити з ними різні операції